name: lifeline
description: Electronic Health Record application.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^0.1.2
 
  # UI
  animated_text_kit: ^3.1.0
  toast: ^0.1.5

  # Loading Animation
  modal_progress_hud: ^0.1.3
  flutter_spinkit: ^4.1.2+1

  # Firebase
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1
  cloud_firestore: ^0.14.4

  #datetime formatter
  intl: ^0.16.1

  #maps
  google_maps_flutter: ^1.0.6
  
  

  #geo-locator
  geolocator: ^6.1.13

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - assets/images/lifeline_logo.png


  fonts:
    - family: Nexa
      fonts:
        - asset: assets/fonts/nexa_light.otf
      
    - family: Nexa Bold
      fonts:
         - asset: assets/fonts/nexa_bold.otf

